package com.dcmc.apps.taskmanager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaskAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskAssignmentAllPropertiesEquals(TaskAssignment expected, TaskAssignment actual) {
        assertTaskAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertTaskAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskAssignmentAllUpdatablePropertiesEquals(TaskAssignment expected, TaskAssignment actual) {
        assertTaskAssignmentUpdatableFieldsEquals(expected, actual);
        assertTaskAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskAssignmentAutoGeneratedPropertiesEquals(TaskAssignment expected, TaskAssignment actual) {
        assertThat(actual)
            .as("Verify TaskAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskAssignmentUpdatableFieldsEquals(TaskAssignment expected, TaskAssignment actual) {
        assertThat(actual)
            .as("Verify TaskAssignment relevant properties")
            .satisfies(a -> assertThat(a.getAssignedAt()).as("check assignedAt").isEqualTo(expected.getAssignedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskAssignmentUpdatableRelationshipsEquals(TaskAssignment expected, TaskAssignment actual) {
        assertThat(actual)
            .as("Verify TaskAssignment relationships")
            .satisfies(a -> assertThat(a.getTask()).as("check task").isEqualTo(expected.getTask()));
    }
}
