package com.dcmc.apps.taskmanager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupAllPropertiesEquals(WorkGroup expected, WorkGroup actual) {
        assertWorkGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupAllUpdatablePropertiesEquals(WorkGroup expected, WorkGroup actual) {
        assertWorkGroupUpdatableFieldsEquals(expected, actual);
        assertWorkGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupAutoGeneratedPropertiesEquals(WorkGroup expected, WorkGroup actual) {
        assertThat(actual)
            .as("Verify WorkGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupUpdatableFieldsEquals(WorkGroup expected, WorkGroup actual) {
        assertThat(actual)
            .as("Verify WorkGroup relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkGroupUpdatableRelationshipsEquals(WorkGroup expected, WorkGroup actual) {
        // empty method
    }
}
